#!/bin/bash

#### Mass connection tests
# 10 Connections
php run_tests name=mass_connections/10_connections/test_1
sleep 1
php run_tests name=mass_connections/10_connections/test_5/
sleep 1
php run_tests name=mass_connections/10_connections/test_10/
sleep 1
# 100 Connections
php run_tests name=mass_connections/100_connections/test_1
sleep 1
php run_tests name=mass_connections/100_connections/test_50/
sleep 1
php run_tests name=mass_connections/100_connections/test_100/
sleep 1
# 1,000 Connections
php run_tests name=mass_connections/1000_connections/test_1
sleep 1
php run_tests name=mass_connections/1000_connections/test_500/
sleep 1
php run_tests name=mass_connections/1000_connections/test_1000/
sleep 1
# 10,000 Connections
php run_tests name=mass_connections/10000_connections/test_1
sleep 1
php run_tests name=mass_connections/10000_connections/test_5000/
sleep 1
php run_tests name=mass_connections/10000_connections/test_10000/
sleep 1
